// Generated by scripts/build-studio-environment.mjs. Do not edit by hand.
export const NIGHT_ENVIRONMENT={
  "width": 1024,
  "height": 512,
  "incoming": [
    -0.0037293817290531862,
    -0.2972340465928168,
    0.9547973676429875
  ],
  "color": [
    1.4917775221423248,
    0.9440589571582275,
    0.10605446860078722
  ],
  "sourceSpread": [
    0.0854655795132838,
    -0.00550199681847048,
    0.09251729970019752
  ],
  "windowFraction": 0.3552919504922966,
  "irradiance": 0.12070603333759117
} as const;
