// Generated by scripts/build-studio-environment.mjs. Do not edit by hand.
export const STUDIO_ENVIRONMENT={
  "width": 1024,
  "height": 512,
  "incoming": [
    0.4938752173898701,
    -0.7482664209591097,
    -0.4429273449598173
  ],
  "color": [
    0.9225870276251623,
    1.0156893657490307,
    1.0725341210967392
  ],
  "sourceSpread": [
    0.1796012143215,
    0.0194246899233279,
    0.1628401982349462
  ],
  "windowFraction": 0.8107974925671884,
  "irradiance": 3.737128394647502
} as const;
